### PR TITLE
Fix QOSF project page rendering.

### PR DESCRIPTION
**Pull request by WrathfulSpatula**
I'm relying on the CI to test deployment, so please hold off on review for a few minutes while I diagnose what will or won't work.

### CODE REVIEW

**Comment by WrathfulSpatula** [comment]
That works! Let's see if it's the `permalink` field's `mime-type`, or if the `id` field will still work, at least.

**Comment by WrathfulSpatula** [comment]
That _doesn't_ work, and the problem does genuinely seem to be `mime-type` served with a `permalink` field. Let's try to restore the `id` field, now.

**Comment by WrathfulSpatula** [comment]
This is ready to review, unless we have a pressing requirement to diagnose the problem with `mime-type` in the framework or app internals, for the `permalink` field.

**Comment by natestemen** [comment]
I'm getting a 404 when navigating to the QOSF page from `/bounties`.

https://deploy-preview-19--unitaryhack2024.netlify.app/projects/quantum-open-source-foundation-qosf

**Review by natestemen — CHANGES_REQUESTED** [review]
I'm getting a 404 when navigating to the QOSF page from /bounties.

https://deploy-preview-19--unitaryhack2024.netlify.app/projects/quantum-open-source-foundation-qosf

I think a simple solution would be to remove `(QOSF)` from the `title`.

**Comment by WrathfulSpatula** [comment]
Closing in favor of 9f40380

**Pull request closed without merging**
